#!/bin/sh
f=./less/css/caiuss.less
#shift
cmd=./build
tmpf="`mktemp /tmp/onchange.XXXXX`"
cp "$f" "$tmpf"
trap "rm $tmpf; exit 1" 2
while : ; do
    if [ "$f" -nt "$tmpf" ]; then
        cp "$f" "$tmpf"
        echo "Building..."
        $cmd
    fi
    sleep 2
done
